version: "3.2"
services:
  api:
    depends_on:
      store:
        condition: service_healthy
    build: ./images/api
    ports:
      - 80:3000
    volumes:
      - ./images/api/src:/user/app/src
    environment:
      PG_CONNECTION_STRING: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@spaceShipsdb:5432/${POSTGRES_DB}"

  
  store:
    container_name: spaceShipsdb
    image: postgres:latest
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 15s
      timeout: 20s
      retries: 5

    ports:
      - 5432:5432
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB:
      POSTGRES_HOSTY_AUTH_METHOD:
    volumes:
      - ./_backup:/var/lib/postgresql/data